"Recipes"
{
	"1"
	{
		"item_frost_salve"
		{
			"Assembly"
			{
				"1" "item_refined_leaf"
				"2" "item_refined_leaf"
				"3" "item_refined_leaf"
				"4" "item_full_bottle"
			}
			"Initial"
			{
				"1" "item_raw_leaf"
				"2" "item_empty_bottle"
			}
		}
		"item_tango_salad"
		{
			"Assembly"
			{
				"1" "item_refined_leaf"
				"2" "item_refined_leaf"
				"3" "item_refined_leaf"
			}
			"Initial"
			{
				"1" "item_raw_leaf"
				"2" "item_raw_leaf"
				"3" "item_raw_leaf"
			}
		}
	}
}